from pyutils.path import join_module_path as _

DEFAULT_WATCH_DIR = _(".")
DEFAULT_WATCH_TMP = _(".tmp")
DEFAULT_SQL_DIR = _("database")
DEFAULT_PVD_DIR = _("./providers")
DEFAULT_LOGFILE = _("openflix.log")
DEFAULT_CONFIG = _("config/localhost.cfg")
DEFAULT_KEYLENGTH = 32
DEFAULT_KEYDIR = "./"
DEFAULT_DATABASE = ":memory:"
DEFAULT_ADMIN_GROUP = "admin"
DEFAULT_GUEST_GROUP = "guest"
DEFAULT_LOGLEVEL = "NOTSET"
DEFAULT_WATCH_EVENT = "IN_ALL_EVENTS"
DEFAULT_PREF_PVD = None
DEFAULT_EXTRA_PVD = list()
DEFAULT_API_METHODS = ("GET", "POST", "PUT", "DELETE")
DEFAULT_USE_CACHE = True
DEFAULT_LANGUAGE = "en"
DEFAULT_TMDB_KEY = "tmdb"
API_SUBDOMAIN = "api"
